apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: sun
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-root-password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-database
        
        
        - name: MYSQL_HOST
          valueFrom:
            configMapKeyRef:
              name: summercamp-config
              key: MYSQL_HOST
        - name: MYSQL_PORT
          valueFrom:
            configMapKeyRef:
              name: summercamp-config
              key: MYSQL_PORT
        
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-user-password
              
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-initdb-volume
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: mysql-initdb-volume
        configMap:
          name: summercamp-config
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
